"""initial_schema

Revision ID: f464729f7673
Revises: 
Create Date: 2026-03-21 00:39:39.804853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f464729f7673'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_class_lookup',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('class_code', sa.String(length=20), nullable=False),
    sa.Column('class_name', sa.String(length=50), nullable=False),
    sa.Column('comparable_with', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_code')
    )
    op.create_table('ingestion_log',
    sa.Column('ingestion_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('source_api', sa.String(length=50), nullable=False),
    sa.Column('file_path_reference', sa.String(length=500), nullable=True),
    sa.Column('schema_hash', sa.String(length=64), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('ingestion_id')
    )
    op.create_table('macro_indicator_master',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('series_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('release_frequency', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_code')
    )
    op.create_table('user_identity',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_identity_email'), 'user_identity', ['email'], unique=True)
    op.create_table('asset_master',
    sa.Column('asset_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('ticker_symbol', sa.String(length=20), nullable=False),
    sa.Column('asset_class_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('denomination_currency', sa.String(length=3), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('status_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_class_id'], ['asset_class_lookup.id'], ),
    sa.PrimaryKeyConstraint('asset_id'),
    sa.UniqueConstraint('ticker_symbol', 'exchange', name='uq_ticker_exchange')
    )
    op.create_index(op.f('ix_asset_master_ticker_symbol'), 'asset_master', ['ticker_symbol'], unique=False)
    op.create_table('order_group',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('strategy_label', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_identity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parquet_manifest',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('ingestion_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('parquet_file_path', sa.String(length=500), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('schema_hash', sa.String(length=64), nullable=True),
    sa.Column('written_at', sa.DateTime(), nullable=False),
    sa.Column('validation_status', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_id'], ['ingestion_log.ingestion_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('objective', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_identity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_user_id'), 'portfolio', ['user_id'], unique=False)
    op.create_table('risk_settings',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('risk_tolerance_level', sa.String(length=20), nullable=True),
    sa.Column('investment_horizon_months', sa.Integer(), nullable=True),
    sa.Column('liquidity_preference', sa.String(length=20), nullable=True),
    sa.Column('sector_exclusions', sa.JSON(), nullable=True),
    sa.Column('max_drawdown_pct', sa.Float(), nullable=True),
    sa.Column('max_exposure_limit', sa.Float(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_identity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_settings_current', 'risk_settings', ['user_id', 'valid_to'], unique=False)
    op.create_index(op.f('ix_risk_settings_user_id'), 'risk_settings', ['user_id'], unique=False)
    op.create_table('asset_subtype_bond',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('asset_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('maturity_date', sa.DateTime(), nullable=True),
    sa.Column('coupon_rate', sa.Float(), nullable=True),
    sa.Column('issuer_type', sa.String(length=20), nullable=True),
    sa.Column('credit_rating', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_master.asset_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id')
    )
    op.create_table('asset_subtype_forex',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('asset_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('quote_currency', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_master.asset_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id')
    )
    op.create_table('comparison_session',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('horizon_months', sa.Integer(), nullable=True),
    sa.Column('assets_compared', sa.JSON(), nullable=True),
    sa.Column('winner_asset_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_identity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_asset_id'], ['asset_master.asset_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_registry',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('asset_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('doc_type', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('filed_at', sa.DateTime(), nullable=True),
    sa.Column('ingestion_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('raw_text_path', sa.String(length=500), nullable=True),
    sa.Column('embedding_status', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_master.asset_id'], ),
    sa.ForeignKeyConstraint(['ingestion_id'], ['ingestion_log.ingestion_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_registry_asset_id'), 'document_registry', ['asset_id'], unique=False)
    op.create_table('position_journal',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('portfolio_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('asset_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('net_quantity', sa.Float(), nullable=False),
    sa.Column('average_cost', sa.Float(), nullable=False),
    sa.Column('position_currency', sa.String(length=3), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl', sa.Float(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_master.asset_id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_identity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_position_current', 'position_journal', ['user_id', 'portfolio_id', 'asset_id', 'is_current'], unique=False)
    op.create_index(op.f('ix_position_journal_is_current'), 'position_journal', ['is_current'], unique=False)
    op.create_index(op.f('ix_position_journal_user_id'), 'position_journal', ['user_id'], unique=False)
    op.create_table('transaction_ledger',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('portfolio_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('asset_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('order_group_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('action_type', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('execution_price', sa.Float(), nullable=False),
    sa.Column('settlement_currency', sa.String(length=3), nullable=False),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('tax_withheld', sa.Float(), nullable=True),
    sa.Column('order_type', sa.String(length=10), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_master.asset_id'], ),
    sa.ForeignKeyConstraint(['order_group_id'], ['order_group.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_identity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_ledger_executed_at'), 'transaction_ledger', ['executed_at'], unique=False)
    op.create_index(op.f('ix_transaction_ledger_user_id'), 'transaction_ledger', ['user_id'], unique=False)
    op.create_table('watchlist',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('portfolio_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('asset_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('sentiment_trigger_high', sa.Float(), nullable=True),
    sa.Column('sentiment_trigger_low', sa.Float(), nullable=True),
    sa.Column('price_trigger_high', sa.Float(), nullable=True),
    sa.Column('price_trigger_low', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_master.asset_id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user_identity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_recommendation_log',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('asset_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('comparison_session_id', mysql.CHAR(length=36), nullable=True),
    sa.Column('recommended_action', sa.String(length=10), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('driving_factors', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('context_snapshot_id', sa.String(length=100), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_master.asset_id'], ),
    sa.ForeignKeyConstraint(['comparison_session_id'], ['comparison_session.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_identity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_recommendation_log_user_id'), 'ai_recommendation_log', ['user_id'], unique=False)
    op.create_table('alert_queue',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('watchlist_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('trigger_value', sa.Float(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_identity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlist.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendation_feedback',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('recommendation_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('user_acted', sa.Boolean(), nullable=True),
    sa.Column('action_taken_at', sa.DateTime(), nullable=True),
    sa.Column('outcome_pct_7d', sa.Float(), nullable=True),
    sa.Column('outcome_pct_30d', sa.Float(), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['ai_recommendation_log.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recommendation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendation_feedback')
    op.drop_table('alert_queue')
    op.drop_index(op.f('ix_ai_recommendation_log_user_id'), table_name='ai_recommendation_log')
    op.drop_table('ai_recommendation_log')
    op.drop_table('watchlist')
    op.drop_index(op.f('ix_transaction_ledger_user_id'), table_name='transaction_ledger')
    op.drop_index(op.f('ix_transaction_ledger_executed_at'), table_name='transaction_ledger')
    op.drop_table('transaction_ledger')
    op.drop_index(op.f('ix_position_journal_user_id'), table_name='position_journal')
    op.drop_index(op.f('ix_position_journal_is_current'), table_name='position_journal')
    op.drop_index('ix_position_current', table_name='position_journal')
    op.drop_table('position_journal')
    op.drop_index(op.f('ix_document_registry_asset_id'), table_name='document_registry')
    op.drop_table('document_registry')
    op.drop_table('comparison_session')
    op.drop_table('asset_subtype_forex')
    op.drop_table('asset_subtype_bond')
    op.drop_index(op.f('ix_risk_settings_user_id'), table_name='risk_settings')
    op.drop_index('ix_risk_settings_current', table_name='risk_settings')
    op.drop_table('risk_settings')
    op.drop_index(op.f('ix_portfolio_user_id'), table_name='portfolio')
    op.drop_table('portfolio')
    op.drop_table('parquet_manifest')
    op.drop_table('order_group')
    op.drop_index(op.f('ix_asset_master_ticker_symbol'), table_name='asset_master')
    op.drop_table('asset_master')
    op.drop_index(op.f('ix_user_identity_email'), table_name='user_identity')
    op.drop_table('user_identity')
    op.drop_table('macro_indicator_master')
    op.drop_table('ingestion_log')
    op.drop_table('asset_class_lookup')
    # ### end Alembic commands ###
